[GLOBAL]

# General
TITLE=RnmrQuant1D
CPRGHT=(C) INRAE UR BIA BIBS 2026
VERSION=1.0.0

# NB MAX CORES (0 means Auto)
CORES=6

# Max ZIP size (Mo)
MAXZIPSIZE=500

# 7zip full path
#ZIP7="C:/Program Files/7-Zip/7z.exe"

# Full path of Rscript
#RSCRIPT="C:/Program Files/R/R-4.3.1/bin/Rscript.exe"
#RSCRIPT="/usr/bin/Rscript"

# Dilution factor by default
DILUTION_FAC=0.8

# Type names for Samples
SAMPLE=Sample

# Type names for Quality Control
QC=QC

# Type names for Quality Standard
QS=QS

