#------------------------------------------------
# ID Tools.R
# Project: RnmrQuant1D
# (C) 2026 - D. JACOB - INRAE
#------------------------------------------------


options(show.error.locations = TRUE)


### Parse the section 'section' within the 'INI.file' file
#   Get the INI.list as an initial list to add or replace the couple of values (key=value)
Parse.INI <- function(INI.file, INI.list=list(), section="GLOBAL")
{
	connection <- file(INI.file)
	Lines  <- readLines(connection)
	close(connection)

	Lines <- chartr("[]", "==", Lines)  # change section headers

	connection <- textConnection(Lines)
	d <- read.table(connection, as.is = TRUE, sep = "=", fill = TRUE)
	close(connection)

	L <- d$V1 == ""                    # location of section breaks
	d <- subset(transform(d, V3 = V2[which(L)[cumsum(L)]])[1:3], V1 != "")
	d <- d[d$V3 == section,]
	
	#INI.list <- list()
	for( i in 1:dim(d)[1] ) {
		if (! is.na(suppressWarnings(as.numeric(d$V2[i])))) {
			eval(parse(text=paste0('INI.list$',d$V1[i], '<-', as.numeric(d$V2[i]))))
			next
		}
		if (! is.na(suppressWarnings(as.logical(d$V2[i])))) {
			eval(parse(text=paste0('INI.list$',d$V1[i], '<-', as.logical(d$V2[i]))))
			next
		}
		eval(parse(text=paste0('INI.list$',d$V1[i], '<-"', d$V2[i],'"')))
	}
	return(INI.list)
}


#----
# Write Text lines 'msg' into file 'filetext'
#----
write_textlines <- function (filetext, msg, mode="at")
{
	fh<-file(filetext,mode)
	writeLines(msg, fh)
	close(fh)
}


#----
# Copy a folder content (source) to another folder (destination)
#----
copy_folder <- function(source, destination)
{
	if (!dir.exists(source))
		stop("The folder does not exist : ", source)

	# Create the destination folder if it does not exist.
	if (!dir.exists(destination))
		dir.create(destination, recursive = TRUE)

	# List all files and subfolders of the source
	lstfiles <- list.files(source, full.names = TRUE, recursive = FALSE)

	# Copy each item to the destination root (avoids nesting)
	out <- file.copy(from = lstfiles, to = destination, recursive = TRUE, overwrite = TRUE)
}


#----
# Delete all files under path
#----
empty_directory <- function(path)
{
	files <- list.files(path, full.names = TRUE, recursive = FALSE, all.files = TRUE, no.. = TRUE)
	unlink(files, recursive = TRUE, force = TRUE)
}


#----
# Executes a method from the RnmrQuant1D package, intercepting —where applicable— 
# the message and interruption generated by the internal `stop_quietly` method.
#----
exe.catch <- function(expr)
{
	message_text <- NULL
	result <- tryCatch({
		withCallingHandlers({
			expr
		}, message = function(m) { # intercept the message
			message_text <<- conditionMessage(m)
			invokeRestart("muffleMessage")  # prevents the message from appearing in the R console
		})
	}, interrupt = function(cnd) { # intercept the interrupt
		NULL
	})
	list(
		result = result,
		message = message_text,
		error_occurred = is.null(result) && !is.null(message_text)
	)
}

#----
# Check if the content of the sample metadata file is compliant with the operation type
#----
check_samples_metadata <- function(rq1d, samples, sdir, vendor, onlyintg)
{
	switch( vendor,
		'bruker' = { colstr <- c("Spectrum", "Samplename", "EXPNO") },
		'varian' = { colstr <- c("Spectrum", "Samplename") },
		'jeol'   = { colstr <- c("Spectrum", "Samplename") }
	)

	ret <- ''
	repeat {
		# Get sample list
		priv <- rq1d$.__enclos_env__$private
		df <- tryCatch({
			priv$get_list_spectrum(sdir, priv$get_list_samples(sdir))
		}, error=function(cond) {
			ret <- paste(cond, collapse="\n")
		})
		if (nchar(ret)) break

		# Check if the samples colnames include the rigth ones
		if (sum(colstr %in% colnames(samples))<length(colstr)) {
			ret <- paste0("Error: the sample colnames must include at least the columns : ",
				paste(colstr,collapse=", "))
			break
		}

		# Samplecodes
		if (vendor=='bruker') {
			samplecode <- paste(samples[,1], samples[,3], sep = "-")
		} else {
			samplecode <- paste(samples[,1],1, sep="-")
		}

		if (!onlyintg) {
			# Check if the samples table has a 'F_dilition' columns
			if (! "F_dilution" %in% colnames(samples)) {
				ret <- "Error: the sample table must have a columns named 'F_dilution'"
				break
			}
			# Check if the samples table has a 'Type' columns
			if (! "Type" %in% colnames(samples)) {
				ret <- "Error: the sample table must have a columns named 'Type'"
				break
			}
			# Check if values of the 'TYPE' columns are valid ones 
			if (sum(! samples$Type %in% sampleTypes)>0) {
				ret <- paste0("Error: Valid values for 'Type' columns are limited to ",
					paste(sampleTypes, collapse=', '))
				break
			}
		}

		# Check whether all spectrum names correspond to a spectrum directory.
		if( sum(samplecode %in% df[,2]) < length(samplecode) ) {
			ret <- paste0("Error: Some spectrum names do not correspond to a spectrum directory:\n",
					paste(samples[ ! samplecode %in% df[,2], 1], collapse=', '))
			break
		}

		# Check whether all spectra have the same frequence
		df <- df[df[,2] %in% samplecode, c(1:4,6:7)]
		freq <- unique(round(as.numeric(df[,5])))
		if ( length(freq)>1 ) {
			ret <- "Error: All spectrum must have the same frequence\n"
			break
		}

		# Check whether all spectra have the same size
		size <- unique(round(as.numeric(df[,6])))
		if ( length(size)>1 ) {
			ret <- "Error: All spectrum must have the same size\n"
			break
		}
		break
	}
	ret
}


#----
# Get the template of sample metadata depending on the operation type
#----
get_samples_metadata <- function(sdir, vendor, onlyintg)
{
	switch( vendor,
		'bruker' = { colstr <- c("Spectrum", "Samplename", "EXPNO") },
		'varian' = { colstr <- c("Spectrum", "Samplename") },
		'jeol'   = { colstr <- c("Spectrum", "Samplename") }
	)

	rq1d <- RnmrQuant1D$new(vendor)
	priv <- rq1d$.__enclos_env__$private

	samples <- priv$get_list_spectrum(sdir, priv$get_list_samples(sdir))
	if (!onlyintg) {
		samples <- cbind( samples[,1:length(colstr)], rep(sampleTypes[1], nrow(samples)), rep(fac_dilution, nrow(samples)) )
		colnames(samples) <- c( colstr, 'Type', rq1d$FDILfield)
		samples$Type[grep(QCQS[1], samples[,1])] <- QCQS[1]
		samples$Type[grep(QCQS[2], samples[,1])] <- QCQS[2]
	} else {
		samples <- samples[,1:length(colstr)]
		colnames(samples) <- colstr
	}
	samples 
}

#----
# Check if file has a XLSX format
#----
is_xlsx <- function(file)
{
	con <- file(file, "rb")
	sig <- readBin(con, "raw", n = 4)
	close(con)  
	# Signature ZIP : 50 4B 03 04
	identical(sig, as.raw(c(0x50, 0x4B, 0x03, 0x04)))
}

#----
# Open the sample file, regardless of its format (TSV or XLSX).
#----
open_samples_file <- function(samplefile)
{
	out <- tryCatch({
		if (is_xlsx(samplefile)) {
			openxlsx::read.xlsx(samplefile, sheet=1)
		} else {
			as.data.frame(utils::read.table(samplefile, sep="\t", header=T,stringsAsFactors=FALSE))
		}
	}, error=function(cond) {
		out <- paste(cond, collapse="\n")
	})
	return(out)
}

#----
# Check if a pattern is valid
#----
is_regex_valide <- function(pattern)
{
	tryCatch({
		grepl(pattern, "test", perl = TRUE)
		TRUE
	}, error = function(e) {
		FALSE
	}, warning = function(w) {
		FALSE
	})
}


#----
# Run a rq1d task in an independent process
#----
submit_rq1d_proc <- function(rq1d, gv, proc='intg', reset=TRUE)
{
	unlink(file.path(rq1d$TMPDIR,"log-*.txt"))
	unlink(file.path(rq1d$TMPDIR,"output_*.txt"))
	unlink(file.path(rq1d$TMPDIR,"ended.out"))
	unlink(file.path(rq1d$TMPDIR,rq1d$cluster_status_file))
	saveRDS(rq1d, file=file.path(gv$outDir,'rq1d.rds'))

	zones <- paste(gv$zones, collapse=",")
	cmpds <- paste(gv$compounds, collapse=",")
	if (proc=='intg') {
		proc_label <- 'Integrals'
		rq1d_cmd <- paste0("rq1d$proc_Integrals(c(",zones,"), ncpu=",gv$ncpu,", progress=FALSE, verbose=2)")
	} else {
		proc_label <- 'Quantification'
		rq1d_cmd <- paste0("rq1d$proc_Quantification(NULL, c(",zones,"), ncpu=",gv$ncpu,", reset=",reset,", progress=FALSE, verbose=1)")
	}

	Rcmd <- paste0("# Compounds: ",cmpds,"
		setwd(\"",gsub("\\\\", "/", gv$outDir),"\")
		rq1d <- readRDS('rq1d.rds')
		sink('rq1d.out')
		t <- system.time({
			tryCatch({
				",rq1d_cmd,"
			}, error=function(e) {
				cat('ERROR: proc_",proc_label," failed :', \"\\n\", paste(e, collapse=\"\\n\"), \"\\n\")
			})
		})
		t
		sink()
		res <- list( rq1d = rq1d, time = t )
		saveRDS(res, file='rq1d.rds')
		fh <- file(file.path(rq1d$TMPDIR,'ended.out'),'wt')
		writeLines('ok', fh)
		close(fh)
	")

	R_script <- file.path(gv$outDir,'Rscript.R')
	write_textlines(R_script, Rcmd, mode="wt")
	CMD <- paste(RSCRIPT, R_script, '2>&1', sep=" ")
	if (OS == "windows") {
		affinity <- sprintf("0x%X", sum(2^(0:(gv$ncpu - 1))))
		system( paste0('cmd.exe /c start /min /affinity ',affinity,' /wait \"RnmrQuant1D Rscript\" ', CMD), wait = FALSE )
	} else if (OS == "unix") {
		system( paste0('taskset -c 0-',gv$ncpu-1, ' ', CMD), wait = FALSE )
	} else {
		system( CMD, wait = FALSE )
	}
	repeat {
		Sys.sleep(1)
		if (file.exists(file.path(rq1d$TMPDIR,rq1d$cluster_status_file))) break
	}
	ret <- file.exists(file.path(rq1d$TMPDIR,'ended.out'))
	return (ret)
}
