[GLOBAL]

# General
TITLE=RnmrQuant1D
CPRGHT=(C) INRAE UR BIA BIBS 2026
VERSION=1.2.2

# Define if DEV mode
DEV=0

# NB MAX CORES (0 means Auto)
CORES=4

# Set affinity
AFFINITY=0

# Max ZIP size (Mo)
MAXZIPSIZE=500

# Maximum number of concurrent sessions 
MAXSESSION=4

# 7zip full path
#ZIP7="C:/Program Files/7-Zip/7z.exe"

# Full path of Rscript
#RSCRIPT=/usr/bin/Rscript

# Dilution factor by default
DILUTION_FAC=0.8

# Type names for Samples
SAMPLE=Sample

# Type names for Quality Control
QC=QC

# Type names for Quality Standard
QS=QS

# Online documentation
CALIBDOC=https://github.com/djacob65/RnmrQuant1D/wiki/2%E2%80%90QC%E2%80%90QS
QUANTDOC=https://github.com/djacob65/RnmrQuant1D/wiki/3%E2%80%90Quantification-profile
